"""
Three animation frames of the circle-cube emblem, one per shaded cube face.

The cube in circle_cube_simple.py is a frame only -- its three faces are cut
out of the silhouette and left as clean voids. Filling exactly one of those
rhombi shades that face; cycling which one gives the impression of the cube
turning.

THE SHADING IS A 50% CHECKERBOARD, not a solid, and it is applied HERE rather
than in the model. A one-pixel checker in build123d would be far below
FINEST_FEATURE (2.36mm, 2.5px at this size) and rasterising it would either
erase it or turn it to noise. Applied to the final bitmap it is exact: every
pixel of the checker is a pixel of the panel, with no resampling in between.

The face region is found by DIFFERENCE rather than by rendering the rhombus on
its own -- a lone rhombus has its own bounding box, so it would rasterise at a
different scale and land in the wrong place. Rendering the emblem with and
without the face and subtracting gives the region in the emblem's own frame.

Writes circlecube_frames.h next to itself. Run with the model venv:
    env -u PYTHONPATH ~/src/models123/.venv/bin/python gen_frames.py
PYTHONPATH must be cleared or the nix PIL shadows the venv's.
"""
import subprocess, sys, os
sys.path.insert(0, os.path.expanduser("~/src/models123"))
os.chdir(os.path.expanduser("~/src/models123"))

import circle_cube_simple as m
from build123d import ExportSVG, Rot, Pos

W = H = 144
STRIDE = W // 8
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "circlecube_frames.h")
TMP = "/tmp/nix-shell.jJ2Trb/claude-1000/-home-jjb-src-zmk-workspace/c097fea1-926a-45af-be5c-a1355a1b95d4/scratchpad"

# Clockwise on screen. The model's FACE_ANGLES are (90, 210, 330) = top,
# lower-left, lower-right, which is the counter-clockwise order; taking the two
# lower faces the other way round turns the cube the way jjb wants.
FACE_ORDER = (90, 330, 210)
FACE_NAME = {90: "top", 210: "lower-left", 330: "lower-right"}


def raster(sketch, name):
    """Render a sketch to a set of ink pixels, in the emblem's own frame."""
    svg, png = f"{TMP}/{name}.svg", f"{TMP}/{name}.png"
    ex = ExportSVG(scale=1)
    ex.add_layer("emblem", fill_color=(0, 0, 0), line_weight=0)
    ex.add_shape(sketch, layer="emblem")
    ex.write(svg)
    subprocess.run(["rsvg-convert", "-w", str(W), "-h", str(H), "-b", "white",
                    svg, "-o", png], check=True)
    from PIL import Image
    img = Image.open(png).convert("L")
    assert img.size == (W, H), img.size
    return {(x, y) for y in range(H) for x in range(W)
            if img.getpixel((x, y)) < 128}          # dark == ink


def pack(pixels):
    rows = []
    for y in range(H):
        row = bytearray(STRIDE)
        for x in range(W):
            if (x, y) in pixels:
                row[x >> 3] |= 0x80 >> (x & 7)
        rows.append(bytes(row))
    return rows


base = raster(m.EMBLEM_SIMPLE, "cc_base")
print(f"bare emblem: {len(base)} of {W*H} px ink ({100*len(base)/(W*H):.0f}%)",
      flush=True)

frames = []
for i, angle in enumerate(FACE_ORDER):
    face = Rot(0, 0, angle - 90) * Pos(0, m.FACE_CENTRE_R) * m.face_rhombus
    filled = raster(m.EMBLEM_SIMPLE + face, f"cc_full{i}")
    region = filled - base
    checker = {(x, y) for (x, y) in region if (x + y) % 2 == 0}
    pixels = base | checker
    frames.append((angle, pack(pixels), len(pixels), len(region), len(checker)))
    print(f"frame {i}: {FACE_NAME[angle]} face ({angle} deg), region {len(region)} px, "
          f"checker {len(checker)} px, total {len(pixels)} "
          f"({100*len(pixels)/(W*H):.0f}%)", flush=True)

with open(OUT, "w") as f:
    f.write("/* generated by circlecube_gen.py -- do not hand-edit */\n")
    for i, (angle, rows, ink, region, checker) in enumerate(frames):
        f.write(f"\n/* {FACE_NAME[angle]} face ({angle} deg) shaded: {region} px of face, "
                f"{checker} checkered, {ink} px ink total "
                f"({100*ink/(W*H):.0f}%) */\n")
        f.write(f"static const uint8_t circlecube_frame{i}[] = {{\n")
        for row in rows:
            f.write("    " + " ".join(f"0x{b:02X}," for b in row) + "\n")
        f.write("};\n")
print("wrote", OUT)
