"""
The circle-cube, full panel height, as ONE antialiased greyscale LVGL image.

This started as the Rolio's generator (../vista508/circlecube_gen.py) and has
ended up somewhere else, because the panel is different in three ways:

  - 240 px instead of 144, since the Qube's panel is 240 tall and the emblem is
    wanted at full height, centred, with the readouts over it;
  - GREYSCALE, not 1-bit. The Rolio's panel has two states per pixel and its
    generator has to threshold; this one has 65536 colours, so the rasteriser's
    own antialiasing is kept and the strokes stop crawling;
  - ONE frame. Rotation is LVGL's job at runtime -- lv_image_set_rotation with
    the software transform, which handles L8 (lv_draw_sw_transform.c) -- so the
    emblem turns at whatever angle the screen asks for rather than stepping
    between pre-rendered frames. Twelve 1-bit frames were 86 KB and still
    looked choppy; one L8 frame is 57.6 KB and is smooth at any angle.

L8 is a luminance format: each byte is how bright that pixel is, which the
display driver turns into grey. So INK_LEVEL below is the emblem's brightness
against a black panel, and everything between 0 and it is antialiasing.

Writes circlecube_img.h next to itself. Run with the model venv:
    env -u PYTHONPATH ~/src/models123/.venv/bin/python circlecube_gen.py
PYTHONPATH must be cleared or the nix PIL shadows the venv's.
"""
import os
import subprocess
import sys

sys.path.insert(0, os.path.expanduser("~/src/models123"))
os.chdir(os.path.expanduser("~/src/models123"))

import circle_cube_simple as m  # noqa: E402

W = H = 240
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "circlecube_img.h")
TMP = os.environ.get("TMPDIR", "/tmp")

# How bright the emblem burns against black. Dark enough that white and
# light-blue text stays readable across it, light enough to read as art.
INK_LEVEL = 0x4E

# Rendered larger and boxed down, so the strokes carry their own antialiasing
# rather than relying on the rasteriser at final size.
SUPERSAMPLE = 3


def raster(sketch, name):
    """Render a sketch to a W*H list of ink coverages, 0 (none) to 255 (full)."""
    from build123d import ExportSVG
    from PIL import Image

    svg, png = f"{TMP}/{name}.svg", f"{TMP}/{name}.png"
    ex = ExportSVG(scale=1)
    ex.add_layer("emblem", fill_color=(0, 0, 0), line_weight=0)
    ex.add_shape(sketch, layer="emblem")
    ex.write(svg)
    big = W * SUPERSAMPLE
    subprocess.run(
        ["rsvg-convert", "-w", str(big), "-h", str(big), "-b", "white", svg, "-o", png],
        check=True,
    )
    img = Image.open(png).convert("L").resize((W, H), Image.LANCZOS)
    # The art is drawn black on white, so coverage is the inverse of luminance.
    return [255 - v for v in img.getdata()]


coverage = raster(m.EMBLEM_SIMPLE, "qube_cc")
pixels = [min(255, c * INK_LEVEL // 255) for c in coverage]
lit = sum(1 for p in pixels if p)
print(f"emblem: {lit} of {W*H} px carry ink ({100*lit/(W*H):.0f}%)", flush=True)

with open(OUT, "w") as f:
    f.write(
        "/*\n"
        " * The circle-cube at full panel height, greyscale, generated by\n"
        " * circlecube_gen.py -- do not hand-edit.\n"
        " *\n"
        " * L8: one byte of luminance per pixel, 0 being the black panel and\n"
        " * the peak being the emblem's grey. The values between are the\n"
        " * rasteriser's antialiasing, which is the point of using L8 here: it\n"
        " * is also the one greyscale format LVGL's software transform can\n"
        " * rotate, so the screen turns this single frame instead of stepping\n"
        " * through pre-rendered ones.\n"
        " */\n"
        "\n"
        "#pragma once\n"
        "\n"
        "#include <lvgl.h>\n"
        "\n"
        f"#define CIRCLECUBE_W {W}\n"
        f"#define CIRCLECUBE_H {H}\n"
        "\n"
        "static const uint8_t circlecube_map[] = {\n"
    )
    for y in range(H):
        row = pixels[y * W : (y + 1) * W]
        for chunk in range(0, W, 24):
            f.write("    " + " ".join(f"0x{v:02X}," for v in row[chunk : chunk + 24]) + "\n")
    f.write(
        "};\n"
        "\n"
        "static const lv_image_dsc_t circlecube_img = {\n"
        "    .header =\n"
        "        {\n"
        "            .magic = LV_IMAGE_HEADER_MAGIC,\n"
        "            .cf = LV_COLOR_FORMAT_L8,\n"
        "            .w = CIRCLECUBE_W,\n"
        "            .h = CIRCLECUBE_H,\n"
        "            .stride = CIRCLECUBE_W,\n"
        "        },\n"
        "    .data_size = sizeof(circlecube_map),\n"
        "    .data = circlecube_map,\n"
        "};\n"
    )
print("wrote", OUT, f"({W * H} bytes of image data)")
