name: Test Local Build Environment
on:
  workflow_dispatch:
  # push:
  #   paths:
  #     - nix/**
  #     - flake.*

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04      # x86_64-linux
          - ubuntu-24.04-arm  # aarch64-linux
          - macos-13          # x86_64-darwin
          - macos-15          # aarch64-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v29
        if: ${{ matrix.os != 'ubuntu-24.04-arm' }}

      # https://github.com/nixbuild/nix-quick-install-action/issues/55
      - uses: cachix/install-nix-action@v30
        if: ${{ matrix.os == 'ubuntu-24.04-arm' }}

      - name: Set up build environment
        run: |
          nix develop --command just init

      - name: Test build recipe
        run: |
          nix develop --command just build planck

      - name: Test draw recipe
        run: |
          nix develop --command just draw
